image: rustlang/rust:nightly

pipelines:
  default:
    - step:
        name: Build project
        artifacts:
            - target/**
        script:
          - cargo build -v
    - parallel:
        - step:
            name: Run tests
            script:
                - cargo test -v
        - step:
            name: Check formatting
            script:
                - rustup component add rustfmt-preview
                - cargo fmt -v -- --check
        - step:
            name: Check clippy
            script:
                - rustup component add clippy-preview
                - touch ./src/main.rs && cargo clippy -- -D warnings
